name: apprise_nodes
channels:
  - knime
  - conda-forge
dependencies:
  - packaging
  - python >= 3.10
  - knime-extension >= 4.7
  - knime-python-base >= 4.7
  - markdown
  - pandas
  - pip >= 20
  - pip:
    - apprise >= 1.2.0